server:
  port: 8001

spring:
  application:
    name: cloud-payment-service1
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/lwm_db?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
rocketmq:
  name-server: 192.168.1.135:9876;192.168.1.138:9876
  consumer:
    group: my-group2
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.atguigu.springcloud.entities
management:
  endpoints:
    web:
      exposure:
        include: '*'